version: '3'
services:
  postgres_db:
    image: postgres:15.0-alpine3.16
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$PG_USER
      - POSTGRES_USER=$PG_PASSWORD
      - POSTGRES_DB=$PG_DATABASE_NAME
    ports:
      - $PG_LOCAL_PORT:$PG_DOCKER_PORT
  server:
    build: server/
    restart: on-failure
    env_file: ./.env
    environment:
      APP_VER: 0.1
      spring.datasource.url : "jdbc:postgresql://postgres_db:$PG_DOCKER_PORT/$PG_DATABASE_NAME"
      spring.datasource.password : "$PG_PASSWORD"
      spring.datasource.username : "$PG_USER"
      spring.jpa.properties.hibernate.dialect : "org.hibernate.dialect.PostgresPlusDialect"
      spring.jpa.hibernate.ddl-auto : "update"
      server.port : "$SPRING_APP_DOCKER_PORT"
    ports:
      - $SPRING_APP_LOCAL_PORT:$SPRING_APP_DOCKER_PORT
    depends_on:
      - postgres_db
  client:
    build: client/
    restart: on-failure
    env_file: ./.env
    ports:
      - $REACT_APP_LOCAL_PORT:$REACT_APP_DOCKER_PORT
    depends_on:
      - server